apiVersion: v1
kind: Pod
metadata:
  labels:
    app: telemetry-processor-azure
  name: telemetry-processor-azure
  annotations:
    dapr.io/enabled: "true" # Do we inject a sidecar into this pod?
    dapr.io/id: "id-telemetry-processor-azure" # Unique ID or Name for Dapr APP (so we can communicate with it)
spec:
  containers:
  - name: telemetry-processor-azure # Name of our container, e.g. `kubectl logs -c c-rw-...`
    image: roadwork.io/telemetry-processor-azure:latest
    imagePullPolicy: Never # Local image! Else IfNotPresent or Always
    env:
    - name: CONNECTION_STRING
      value: ""
  restartPolicy: OnFailure # OnFailure since sometimes we fail to identify the GRPC channel